server:
  port: 9050
  servlet:
    context-path: /
spring:
  application:
    name: zuul                          #定义服务名称
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7000/eureka
  instance:
    instance-id: zuul-9050              #定义微服务的名称
    prefer-ip-address: true             #是否显示IP和端口

zuul:
  prefix: /api                          #通过统一的公共前缀访问
#  ignored-services: springcloud-user   #禁止通过某个服务名访问
  ignored-services: "*"                 #禁止通过全部服务名访问
  routes:
    user-service:
      serviceId: consumer-user          #映射的服务名称
      path:      /user/**               #浏览器输入地址

management:                             #路由映射显示
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS